
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - esbenp.prettier-vscode

# Suspiciously/possibly not really necessary if you want to use the
# Ruby Docker image, not really Ruby inside the container. Might be useful.
# NOTE: This is slow AF, consider using `ruby-full` from Ubuntu upstream.
tasks:
  - name: Faster rvm based Ruby-env management.
    init: >
      sudo apt update -y &&
      sudo apt-get install -y curl g++ gcc autoconf automake bison libc6-dev libffi-dev libgdbm-dev \
        libncurses5-dev libsqlite3-dev libtool libyaml-dev make pkg-config \
        sqlite3 zlib1g-dev libgmp-dev libreadline-dev libssl-dev &&
      curl -sSL https://get.rvm.io | bash -s stable --rails &&
      rvm reinstall 3.0.3 &&
      rvm use 3.0.3 &&
      rvm rubygems --force latest &&
      rvm get stable --auto-dotfiles &&
      eval $SHELL
    command: rvm use 3.0.3